language: scala

scala:
  - 2.12.13
  - 2.13.2

sudo: false

jdk:
  - openjdk8

env:
  - TRAVIS_NODE_VERSION="10.17.0"
  - TRAVIS_NODE_VERSION="12.13.1"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts assembleAkkaLibrary
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test:fastOptJS
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsTestkitJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaActorTestJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsStreamTestkitJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaStreamTestJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsTypedTestkitJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaTypedTestJS/test
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts akkaJsActorStreamTypedJS/test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm | true
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm | true
  - find $HOME/.cache -name "*.lock" | xargs rm | true
  - find $HOME/.cache -name "ivydata-*.properties" | xargs rm | true
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache/
